# -------------------- Import Modules --------------------
import os

import pandas as pd

from Cornus.Data_Hunter.HuntingDataCore import HuntingDataCore
from Cornus.MetaUnits.VisionCore import VisionCore

BASED_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CSV_DIR = os.path.join(BASED_PATH, "Clarify_Report")
CLEANED_DIR = os.path.join(BASED_PATH, "Cleaned_Dataset")

os.makedirs(CSV_DIR, exist_ok=True)
os.makedirs(CLEANED_DIR, exist_ok=True)
# -------------------- Clarity core --------------------
class ClarityCore:
    """
    Data cleaning core for DataFrame-based workflows.

    `ClarityCore` is designed as the dedicated cleaning layer of the project.
    It receives a loaded dataset from `HuntingDataCore`, optionally uses report
    information from `VisionCore`, and applies cleaning operations to a working
    copy of the source data.

    Purpose
    -------
    The class centralizes common manual and semi-automated cleaning operations
    such as dropping rows, dropping columns, handling missing values, removing
    duplicates, trimming string whitespace, and replacing specified values.

    Data Flow
    ---------
    - `source_data` stores the original loaded dataset from `HuntingDataCore`
    - `vision_data` stores report information from `VisionCore`
    - `cleaned_data` stores the current mutable working copy used for cleaning

    Attributes
    ----------
    hunter_core : HuntingDataCore
        Data-loading core that provides the original target dataset.
    vision_core : VisionCore
        Inspection/report core that may provide pre-cleaning report output.
    source_data : pandas.DataFrame or None
        Original dataset loaded from `HuntingDataCore`.
    vision_data : dict or None
        Report dictionary obtained from `VisionCore`.
    cleaned_data : pandas.DataFrame or None
        Working copy of `source_data` used for cleaning operations.
    cleaned_data_report : dict or None
        Reserved container for cleaned-data report summaries.
    cleaning_history : list[dict]
        Ordered list of cleaning-operation records generated by
        `_record_history()`.

    General Behavior
    ----------------
    Most public cleaning methods:
    - validate the current working data
    - optionally validate target columns or parameters
    - create a cleaned DataFrame copy
    - record the operation into `cleaning_history`
    - either update `self.cleaned_data` or return a preview copy depending on
    `inplace`

    When a cleaning method is executed with `inplace=True`, the updated
    `cleaned_data` may also be exported automatically as a CSV file under the
    project working directory's `Cleaned_Dataset` folder.

    Notes
    -----
    This class is intended to keep cleaning concerns separate from loading and
    inspection concerns, making the overall project easier to maintain and
    extend.

    The automatic cleaned-data export is intended to preserve the latest stored
    working dataset as a separate CSV snapshot, while cleaning history records
    continue to be managed independently through `_record_history()`.
    """

    # -------------------- Initialization --------------------
    def __init__(self, hunter_core: HuntingDataCore, vision_core: VisionCore):
        """
        Initialize the cleaning core with loaded data and optional report context.

        Parameters
        ----------
        hunter_core : HuntingDataCore
            A `HuntingDataCore` instance that contains the loaded target dataset.
        vision_core : VisionCore
            A `VisionCore` instance that may contain report information describing
            the loaded dataset.

        Attributes Initialized
        ----------------------
        hunter_core : HuntingDataCore
            Stored reference to the incoming loading core.
        vision_core : VisionCore
            Stored reference to the incoming inspection core.
        source_data : pandas.DataFrame or None
            Raw loaded dataset from `hunter_core.target_data`.
        vision_data : dict or None
            Inspection/report dictionary from `vision_core.target_data_report`.
        cleaned_data : pandas.DataFrame or None
            Working copy of `source_data` used for all cleaning operations.
        cleaned_data_report : dict or None
            Placeholder for future cleaned-data summary information.
        cleaning_history : list[dict]
            Empty list used to store step-by-step cleaning history records.

        Notes
        -----
        `source_data` is intended to remain as the original dataset snapshot,
        while `cleaned_data` is the mutable working copy used during cleaning.
        """
        # ---------- Cores initialization / Data setup ----------
        self.hunter_core = hunter_core  # HuntingDataCore object
        self.vision_core = vision_core  # VisionCore object

        self.source_data = hunter_core.target_data  # HuntingDataCore loaded target data
        self.vision_data = vision_core.target_data_report  # VisionCore data report
        self.cleaned_data = (
            self.source_data.copy() if self.source_data is not None else None
        )

        self.cleaned_data_report: dict = None  # Record cleaned data report
        self.cleaning_history: list[dict] = []  # Record cleaned history

    # -------------------- Validation (helper) --------------------
    def _validation(self):
        """
        Validate whether the current working dataset is available and cleanable.

        This helper verifies that `self.cleaned_data` exists, is a pandas
        DataFrame, and is not empty before any cleaning operation proceeds.

        Returns
        -------
        bool
            `True` if `self.cleaned_data` is available, is a DataFrame, and is not
            empty; otherwise `False`.

        Side Effects
        ------------
        Prints warning messages to the console when validation fails.

        Validation Rules
        ----------------
        The method checks whether:
        - `self.cleaned_data` is not `None`
        - `self.cleaned_data` is a pandas DataFrame
        - `self.cleaned_data` is not empty

        Notes
        -----
        This method is intended to be called at the beginning of most public
        cleaning methods.
        """
        if self.cleaned_data is None:
            print("⚠️ No data available ‼️")
            return False

        if not isinstance(self.cleaned_data, pd.DataFrame):
            print("⚠️ Data must be a pandas DataFrame ‼️")
            return False

        if self.cleaned_data.empty:
            print("⚠️ Data is empty ‼️")
            return False

        return True

    # -------------------- View data before cleaning (helper) --------------------
    def _view_data_before_cleaning(self):
        """
        Display available pre-cleaning report information before a cleaning operation.

        This helper validates that the current working dataset is available and, when
        possible, prints a null-value summary report generated earlier by
        ``VisionCore``. It is intended as an optional pre-cleaning inspection step so
        the user can quickly review missing-value conditions before applying cleaning
        methods.

        Returns
        -------
        None
            This helper does not return cleaned data or a report object.
            - Returns ``None`` immediately if the current working dataset fails
            validation.
            - Otherwise prints available pre-cleaning report information to the console.

        Behavior
        --------
        - Calls ``self._validation()`` to confirm that ``self.cleaned_data`` exists,
        is a ``pandas.DataFrame``, and is not empty.
        - If validation fails, the method stops and returns ``None``.
        - If ``self.vision_data`` exists and contains the key ``"null_report"``,
        prints that null-summary report.
        - If no null report is available, prints a warning message instead.

        Side Effects
        ------------
        - Prints pre-cleaning diagnostic information to the console.
        - Does not modify ``self.cleaned_data``.
        - Does not update ``self.cleaned_data_report``.
        - Does not append any entry to ``self.cleaning_history``.

        Notes
        -----
        - This helper is mainly for interactive or menu-driven workflows where the user
        may want to inspect null-related report information before choosing a
        cleaning action.
        - The method depends on report data previously prepared by ``VisionCore`` and
        stored in ``self.vision_data``.
        - If ``VisionCore`` did not generate a ``"null_report"``, this helper only
        prints a warning and performs no further action.
        """
        if not self._validation():
            return None

        if self.vision_data is not None and "null_report" in self.vision_data:
            print(
                f"🕯️ Before cleaning data, viewing data report for null\n{self.vision_data['null_report']}"
            )
        else:
            print("⚠️ No null report available ‼️")

    # -------------------- Cleaning history (helper) --------------------
    def _record_history(
        self,
        action: str,
        before_shape: tuple,
        after_shape: tuple,
        details: dict = None,
        data_for_report: pd.DataFrame = None,
        save_csv: bool = True,
    ):
        """
        Record one cleaning operation, update the latest cleaning summary, and
        optionally export the accumulated history to CSV.

        This helper centralizes three internal responsibilities after a cleaning
        operation has been completed:

        1. build and append a structured history record into `self.cleaning_history`
        2. update `self.cleaned_data_report` using the provided result DataFrame
        3. save the full cleaning history table to a CSV file when requested

        Parameters
        ----------
        action : str
            Name of the cleaning action being recorded, such as
            `"drop_duplicates"`, `"fill_values_in_data"`, or `"replace_values"`.
        before_shape : tuple
            Shape of the dataset before the cleaning operation, typically in the
            form `(rows, columns)`.
        after_shape : tuple
            Shape of the dataset after the cleaning operation, typically in the
            form `(rows, columns)`.
        details : dict, optional
            Additional metadata describing the operation. Typical examples include
            target columns, removed row counts, replacement values, changed cell
            counts, and `inplace` status. If `None`, an empty dictionary is used.
        data_for_report : pandas.DataFrame, optional
            Result DataFrame used to refresh `self.cleaned_data_report`. When this
            argument is a valid DataFrame, the method computes a lightweight summary
            of that result, including shape, missing-value count, duplicate-row
            count, last action, and history length.
        save_csv : bool, default=True
            Whether to export the full accumulated cleaning history to a CSV file.

        Returns
        -------
        dict
            A flattened history record dictionary representing the current cleaning
            step.

        Recorded Fields
        ---------------
        The returned and stored history record contains:

        - `step`
        - `action`
        - `before_rows`
        - `before_cols`
        - `after_rows`
        - `after_cols`
        - `row_change`
        - `col_change`

        In addition, all key-value pairs from `details` are expanded directly into
        the same record.

        Updated Summary Report
        ----------------------
        When `data_for_report` is a valid pandas DataFrame, `self.cleaned_data_report`
        is updated with:

        - `current_shape`
        - `row_count`
        - `column_count`
        - `missing_cells`
        - `duplicate_rows`
        - `last_action`
        - `last_details`
        - `history_count`

        Important Behavior
        ------------------
        `self.cleaned_data_report` reflects the DataFrame passed through
        `data_for_report`, not necessarily the currently stored `self.cleaned_data`.

        This means:
        - if a method performs a preview-style cleaning result and passes that
        preview DataFrame into `data_for_report`, the summary report will describe
        that preview result
        - if the caller later decides not to assign the preview result back into
        `self.cleaned_data`, the summary report may describe the most recent
        operation result rather than the class's formally stored working data

        CSV Export Behavior
        -------------------
        When `save_csv=True` and `hunter_core.current_file_path` is available, the
        method exports the full `self.cleaning_history` list as a CSV file named:

        `{base_name}_Cleaning_Record.csv`

        The file is saved under `CSV_DIR` using UTF-8 with BOM
        (`encoding="utf-8-sig"`), which is often convenient for spreadsheet tools.

        If `save_csv=True` but no current file path is available, a warning message
        is printed and no CSV file is written.

        Side Effects
        ------------
        - appends a new record to `self.cleaning_history`
        - may update `self.cleaned_data_report`
        - may write the full cleaning history to disk as a CSV file

        Notes
        -----
        This method is intended for internal use by cleaning methods and provides a
        single consistent mechanism for history tracking, report updating, and
        optional persistence of cleaning records.
        """
        details = details or {}

        # ---------- Record cleaning actions ----------
        record = {
            "step": len(self.cleaning_history) + 1,
            "action": action,
            "before_rows": before_shape[0] if before_shape else None,
            "before_cols": before_shape[1] if before_shape else None,
            "after_rows": after_shape[0] if after_shape else None,
            "after_cols": after_shape[1] if after_shape else None,
            "row_change": (
                (after_shape[0] - before_shape[0])  # Calculate rows changed
                if before_shape and after_shape
                else None
            ),
            "col_change": (
                (after_shape[1] - before_shape[1])  # Calculate columns changed
                if before_shape and after_shape
                else None
            ),
            **details,
        }

        self.cleaning_history.append(record)

        # ---------- Record cleaned data report ----------
        if isinstance(data_for_report, pd.DataFrame):
            self.cleaned_data_report = {
                "current_shape": data_for_report.shape,
                "row_count": data_for_report.shape[0],
                "column_count": data_for_report.shape[1],
                "missing_cells": int(data_for_report.isna().sum().sum()),
                "duplicate_rows": int(data_for_report.duplicated().sum()),
                "last_action": action,
                "last_details": details,
                "history_count": len(self.cleaning_history),
            }

        current_file_path = getattr(self.hunter_core, "current_file_path", None)

        if save_csv and current_file_path:
            history_df = pd.DataFrame(self.cleaning_history)
            base_name = os.path.splitext(os.path.basename(current_file_path))[0]
            save_path = os.path.join(CSV_DIR, f"{base_name}_Cleaning_Record.csv")
            history_df.to_csv(save_path, index=False, encoding="utf-8-sig")
        elif save_csv:
            print("⚠️ No current file path available, CSV record was not saved ‼️")

        return record

    # -------------------- Save cleaned dataset (helper) --------------------
    def _save_cleaned_dataset(self):
        """
        Save the current cleaned dataset to the `Cleaned_Dataset` folder.

        This helper exports `self.cleaned_data` as a CSV file using the current
        source file name as the base name. The output file is saved under the
        project working directory's `Cleaned_Dataset` folder so that the latest
        stored cleaned dataset can be preserved outside the class instance.

        Returns
        -------
        str or None
            Full save path if the file is successfully written; otherwise `None`.

        Behavior
        --------
        - Validates that `self.cleaned_data` is available
        - Retrieves `hunter_core.current_file_path`
        - Uses the source file name to build the output CSV name
        - Saves `self.cleaned_data` to disk using UTF-8 with BOM
        (`encoding="utf-8-sig"`)
        - Prints a success or warning message

        Saved Filename
        --------------
        The saved filename format is:

        `{base_name}_Cleaned_Data.csv`

        Side Effects
        ------------
        - Writes the current `self.cleaned_data` to disk as a CSV file
        - Prints a success or warning message to the console

        Notes
        -----
        - This helper is intended for internal use after `self.cleaned_data` has been
        updated by a cleaning method.
        - The method requires both `self.cleaned_data` and
        `self.hunter_core.current_file_path` to be available.
        - This helper saves the full cleaned dataset, not the cleaning history and
        not a lightweight summary report.
        """
        if self.cleaned_data is None:
            print("⚠️ No cleaned data available to save ‼️")
            return None

        current_file_path = getattr(self.hunter_core, "current_file_path", None)
        if not current_file_path:
            print("⚠️ No current file path available, cleaned dataset was not saved ‼️")
            return None

        # ---------- Get data name as file's name ----------
        base_name = os.path.splitext(os.path.basename(current_file_path))[0]
        save_path = os.path.join(CLEANED_DIR, f"{base_name}_Cleaned_Data.csv")

        self.cleaned_data.to_csv(save_path, index=False, encoding="utf-8-sig")
        print(f"🔥 Cleaned dataset saved in --->\n{save_path}")
        return save_path

    # -------------------- Drop values in each rows --------------------
    def drop_rows_by_value_core(
        self,
        target_columns: list[str] = None,
        drop_values: list[str | int | float] = None,
        inplace: bool = False,
    ):
        """
        Drop rows containing specified values.

        This method removes rows from `self.cleaned_data` when one or more target
        columns contain any value listed in `drop_values`. If `target_columns` is
        not provided, the search is performed across all columns.

        Parameters
        ----------
        target_columns : list[str], optional
            Column names to inspect for matching values. If `None`, all columns in
            the working dataset are checked.
        drop_values : list[str | int | float], optional
            Values that trigger row removal when found in the inspected columns.
            This argument must not be `None`.
        inplace : bool, default=False
            If `True`, update `self.cleaned_data` with the cleaned result.
            If `False`, return a cleaned preview without modifying the class state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame after removing matched rows, or `None` if validation
            fails or input parameters are invalid.

        Behavior
        --------
        - Validates the working dataset
        - Validates `drop_values`
        - Optionally validates `target_columns`
        - Builds a row-level boolean mask using `.isin(...).any(axis=1)`
        - Removes rows matching the condition
        - Records the cleaning action in `cleaning_history`
        - Either updates `self.cleaned_data` or returns a preview copy
        - When `inplace=True`, also saves the updated cleaned dataset as a CSV file
        under `Cleaned_Dataset`

        History Details
        ---------------
        The recorded history entry includes:
        - `target_columns`
        - `drop_values`
        - `removed_rows`
        - `inplace`

        Side Effects
        ------------
        May update `self.cleaned_data`, append a history record, save the updated
        cleaned dataset to disk when `inplace=True`, and print preview or update
        messages.

        Notes
        -----
        This method removes entire rows if any inspected cell matches one of the
        specified `drop_values`.
        """
        if not self._validation():
            return None

        if drop_values is None:
            print("⚠️ Drop values cannot be None ‼️")
            return None

        # ---------- Build condition mask ----------
        if target_columns is None:
            row_mask = self.cleaned_data.isin(drop_values).any(axis=1) # Check dropped value in each row direction
        else:
            # ---------- Check missing columns ----------
            missing_cols = [
                col for col in target_columns if col not in self.cleaned_data.columns
            ]
            if missing_cols:
                print(f"⚠️ Columns not found: {missing_cols} ‼️")
                return None

            row_mask = (
                self.cleaned_data[target_columns].isin(drop_values).any(axis=1)
            )  # Series format

        # ---------- Drop matched rows ----------
        cleaning_data = self.cleaned_data.loc[
            ~row_mask
        ].copy()  # Cleaned data by masking

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,
            action="drop_rows_by_value",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "target_columns": target_columns,
                "drop_values": drop_values,
                "removed_rows": int(row_mask.sum()),
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data

        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data

    # -------------------- Drop rows --------------------
    def drop_rows_core(
        self,
        target_index: list = None,
        inplace: bool = False,
    ):
        """
        Drop selected rows by index labels.

        This method removes rows from the working dataset by directly specifying
        row index labels. It is the row-oriented counterpart of
        `drop_columns_core()`, which removes columns by name.

        Parameters
        ----------
        target_index : list, optional
            Row index labels to remove from `self.cleaned_data`.
            This argument must not be `None`.
        inplace : bool, default=False
            If `True`, update `self.cleaned_data` with the cleaned result.
            If `False`, return a cleaned preview without modifying the class
            state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame with selected rows removed, or `None` if
            validation fails or requested index labels are invalid.

        Behavior
        --------
        - Validates the working dataset
        - Validates `target_index`
        - Confirms that all requested index labels exist
        - Drops the requested rows by index label
        - Records the action in `cleaning_history`
        - Either updates `self.cleaned_data` or returns a preview copy
        - When `inplace=True`, the updated cleaned dataset may also be saved as a
        CSV file under `Cleaned_Dataset`

        History Details
        ---------------
        The recorded history entry includes:
        - `target_index`
        - `removed_rows`
        - `inplace`

        Side Effects
        ------------
        May update `self.cleaned_data`, append a history record, save the updated
        cleaned dataset to disk when `inplace=True`, and print preview or update
        messages.

        Notes
        -----
        This method removes rows directly by index label and does not inspect
        the values stored inside the rows.
        """
        if not self._validation():
            return None

        if target_index is None:
            print("⚠️ Target index cannot be None ‼️")
            return None

        # ---------- Check missing index labels ----------
        missing_index = [
            idx for idx in target_index if idx not in self.cleaned_data.index
        ]
        if missing_index:
            print(f"⚠️ Index labels not found: {missing_index} ‼️")
            return None

        # ---------- Drop selected rows ----------
        cleaning_data = self.cleaned_data.drop(index=target_index).copy()

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,  # Record data after cleaning
            action="drop_rows",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "target_index": target_index,
                "removed_rows": len(target_index),
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data
        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data

    # -------------------- Drop values in each columns --------------------
    def drop_columns_by_value_core(
        self,
        target_columns: list[str] = None,
        drop_values: list[str | int | float] = None,
        inplace: bool = False,
    ):
        """
        Drop columns containing specified values.

        This method removes columns from `self.cleaned_data` when one or more
        inspected cells contain any value listed in `drop_values`. If
        `target_columns` is not provided, all columns in the working dataset are
        checked.

        Parameters
        ----------
        target_columns : list[str], optional
            Column names to inspect for matching values. If `None`, all columns in
            the working dataset are inspected.
        drop_values : list[str | int | float], optional
            Values that trigger column removal when found anywhere inside an
            inspected column. This argument must not be `None`.
        inplace : bool, default=False
            If `True`, update `self.cleaned_data` with the cleaned result.
            If `False`, return a cleaned preview without modifying the class state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame after removing matched columns, or `None` if
            validation fails or parameters are invalid.

        Behavior
        --------
        - Validates the working dataset
        - Validates `drop_values`
        - Uses all columns if `target_columns` is `None`
        - Validates target column existence if columns are specified
        - Builds a column-level boolean mask using `.isin(...).any(axis=0)`
        - Identifies matching columns
        - Drops those columns from the working dataset copy
        - Records the action in `cleaning_history`
        - Either updates `self.cleaned_data` or returns a preview copy
        - When `inplace=True`, the updated cleaned dataset may also be saved as a
        CSV file under `Cleaned_Dataset`

        History Details
        ---------------
        The recorded history entry includes:
        - `target_columns`
        - `drop_values`
        - `removed_columns`
        - `inplace`

        Side Effects
        ------------
        May update `self.cleaned_data`, append a history record, save the updated
        cleaned dataset to disk when `inplace=True`, and print preview or update
        messages.

        Notes
        -----
        This method is useful when certain sentinel or invalid values indicate that
        a whole column should be discarded.
        """
        if not self._validation():
            return None

        if drop_values is None:
            print("⚠️ Drop values cannot be None ‼️")
            return None

        if target_columns is None:
            target_columns = self.cleaned_data.columns.tolist()
        else:
            missing_cols = [
                col for col in target_columns if col not in self.cleaned_data.columns
            ]
            if missing_cols:
                print(f"⚠️ Columns not found: {missing_cols} ‼️")
                return None

        # ---------- Build column mask ----------
        col_mask = self.cleaned_data[target_columns].isin(drop_values).any(axis=0)

        # ---------- Select columns matching the mask to drop ----------
        matched_columns = col_mask[col_mask].index.tolist()

        # ---------- Drop matched columns ----------
        cleaning_data = self.cleaned_data.drop(columns=matched_columns).copy()

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,  # Record data after cleaning
            action="drop_columns_by_value",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "target_columns": target_columns,
                "drop_values": drop_values,
                "removed_columns": matched_columns,
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data
        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data

    # -------------------- Drop columns --------------------
    def drop_columns_core(
        self,
        target_columns: list[str] = None,
        inplace: bool = False,
    ):
        """
        Drop selected columns by column name.

        This method removes explicitly specified columns from the working dataset.

        Parameters
        ----------
        target_columns : list[str], optional
            Column names to remove from `self.cleaned_data`. This argument must not
            be `None`.
        inplace : bool, default=False
            If `True`, update `self.cleaned_data` with the cleaned result.
            If `False`, return a cleaned preview without modifying the class state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame with selected columns removed, or `None` if
            validation fails or requested columns are invalid.

        Behavior
        --------
        - Validates the working dataset
        - Validates `target_columns`
        - Confirms that all requested columns exist
        - Drops the requested columns
        - Records the action in `cleaning_history`
        - Either updates `self.cleaned_data` or returns a preview copy
        - When `inplace=True`, the updated cleaned dataset may also be saved as a
        CSV file under `Cleaned_Dataset`

        History Details
        ---------------
        The recorded history entry includes:
        - `target_columns`
        - `removed_columns`
        - `inplace`

        Side Effects
        ------------
        May update `self.cleaned_data`, append a history record, save the updated
        cleaned dataset to disk when `inplace=True`, and print preview or update
        messages.

        Notes
        -----
        This method removes columns directly by name and does not inspect the
        column contents.
        """
        if not self._validation():
            return None

        if target_columns is None:
            print("⚠️ Target columns cannot be None ‼️")
            return None

        # ---------- Check missing columns ----------
        missing_cols = [
            col for col in target_columns if col not in self.cleaned_data.columns
        ]
        if missing_cols:
            print(f"⚠️ Columns not found: {missing_cols} ‼️")
            return None

        # ---------- Drop selected columns ----------
        cleaning_data = self.cleaned_data.drop(columns=target_columns).copy()

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,  # Record data after cleaning
            action="drop_columns",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "target_columns": target_columns,
                "removed_columns": len(target_columns),
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data
        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data

    # -------------------- Drop missing values in data --------------------
    def drop_missing_values(
        self,
        target_columns: list[str] = None,
        how: str = "any",
        inplace: bool = False,
    ):
        """
        Drop rows containing missing values.

        This method removes rows from `self.cleaned_data` based on missing-value
        rules. It can inspect all columns or a selected subset of columns, and it
        supports dropping rows where any or all inspected cells are missing.

        Parameters
        ----------
        target_columns : list[str], optional
            Column names to inspect for missing values. If `None`, all columns are
            considered.
        how : str, default="any"
            Missing-value rule used by pandas `dropna()`:

            - `"any"` removes rows with at least one missing value in the inspected
            columns
            - `"all"` removes rows only when all inspected columns are missing
        inplace : bool, default=False
            If `True`, update `self.cleaned_data` with the cleaned result.
            If `False`, return a cleaned preview without modifying the class state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame with missing-value rows removed, or `None` if
            validation fails or parameters are invalid.

        Behavior
        --------
        - Validates the working dataset
        - Validates `how`
        - Optionally validates `target_columns`
        - Uses `dropna(how=...)` across all columns when `target_columns` is `None`
        - Uses `dropna(subset=target_columns, how=...)` for selected columns
        - Records the action in `cleaning_history`
        - Either updates `self.cleaned_data` or returns a preview copy
        - When `inplace=True`, the updated cleaned dataset may also be saved as a
        CSV file under `Cleaned_Dataset`

        History Details
        ---------------
        The recorded history entry includes:
        - `target_columns`
        - `how`
        - `removed_rows`
        - `inplace`

        Side Effects
        ------------
        May update `self.cleaned_data`, append a history record, save the updated
        cleaned dataset to disk when `inplace=True`, and print preview or update
        messages.

        Notes
        -----
        This method removes entire rows, not individual missing cells.
        """
        if not self._validation():
            return None

        # ---------- Dropping mode (how) ----------
        how = how.lower().strip()
        if how not in ["any", "all"]:
            print("⚠️ how must be 'any' or 'all' ‼️")
            return None

        # ---------- Check missing columns ----------
        if target_columns is not None:
            missing_cols = [
                col for col in target_columns if col not in self.cleaned_data.columns
            ]
            if missing_cols:
                print(f"⚠️ Columns not found: {missing_cols} ‼️")
                return None

        # ---------- Drop missing values ----------
        if target_columns is None:
            cleaning_data = self.cleaned_data.dropna(how=how).copy()  # All columns
        else:
            cleaning_data = self.cleaned_data.dropna( # Certain columns
                subset=target_columns, how=how
            ).copy()  # Selected columns

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,  # Record data after cleaning
            action="drop_missing_values",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "target_columns": target_columns,
                "how": how,
                "removed_rows": before_shape[0] - after_shape[0],
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data
        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data

    # -------------------- Drop duplicates in data --------------------
    def drop_duplicates(
        self,
        subset: list[str] = None,
        keep: str = "first",
        inplace: bool = False,
    ):
        """
        Drop duplicate rows from the working dataset.

        This method removes duplicate rows from `self.cleaned_data` using pandas
        `drop_duplicates()`. Duplicate detection may be based on all columns or on
        a selected subset of columns.

        Parameters
        ----------
        subset : list[str], optional
            Column names used to identify duplicates. If `None`, all columns are
            considered.
        keep : str, default="first"
            Duplicate-retention rule:

            - `"first"` keeps the first occurrence
            - `"last"` keeps the last occurrence
            - `"false"` removes all duplicated rows
        inplace : bool, default=False
            If `True`, update `self.cleaned_data` with the cleaned result.
            If `False`, return a cleaned preview without modifying the class state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame with duplicate rows removed, or `None` if validation
            fails or parameters are invalid.

        Behavior
        --------
        - Validates the working dataset
        - Validates `keep`
        - Converts `"false"` to the boolean `False`
        - Optionally validates `subset` columns
        - Removes duplicates using pandas `drop_duplicates()`
        - Records the action in `cleaning_history`
        - Either updates `self.cleaned_data` or returns a preview copy
        - When `inplace=True`, the updated cleaned dataset may also be saved as a
        CSV file under `Cleaned_Dataset`

        History Details
        ---------------
        The recorded history entry includes:
        - `subset`
        - `keep`
        - `removed_rows`
        - `inplace`

        Side Effects
        ------------
        May update `self.cleaned_data`, append a history record, save the updated
        cleaned dataset to disk when `inplace=True`, and print preview or update
        messages.

        Notes
        -----
        This method operates at the row level and does not modify values within
        cells.
        """
        if not self._validation():
            return None

        # ---------- Remain modes ----------
        keep = keep.lower().strip()
        if keep not in ["first", "last", "false"]:
            print("⚠️ keep must be 'first', 'last', or 'false' ‼️")
            return None

        if keep == "false":
            keep = False

        # ---------- Check missing columns ----------
        if subset is not None:
            missing_cols = [
                col for col in subset if col not in self.cleaned_data.columns
            ]
            if missing_cols:
                print(f"⚠️ Columns not found: {missing_cols} ‼️")
                return None

        # ---------- Drop duplicates ----------
        cleaning_data = self.cleaned_data.drop_duplicates(
            subset=subset, keep=keep
        ).copy()

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,  # Record data after cleaning
            action="drop_duplicates",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "subset": subset,
                "keep": keep,
                "removed_rows": before_shape[0] - after_shape[0],
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data
        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data

    # -------------------- Fill values for missing values --------------------
    def fill_values_in_data(
        self,
        fill_value,
        target_columns: list[str] = None,
        inplace: bool = False,
    ):
        """
        Fill missing values with a fixed value.

        This method replaces missing values in the working dataset using a single
        user-provided `fill_value`. Filling may be applied to all columns or to a
        selected subset of columns.

        Parameters
        ----------
        fill_value : Any
            Value used to replace missing entries.
        target_columns : list[str], optional
            Column names to fill. If `None`, all columns in the working dataset are
            filled.
        inplace : bool, default=False
            If `True`, update `self.cleaned_data` with the cleaned result.
            If `False`, return a cleaned preview without modifying the class state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame with missing values filled, or `None` if validation
            fails or parameters are invalid.

        Behavior
        --------
        - Validates the working dataset
        - Optionally validates `target_columns`
        - If columns are specified, fills missing values only in those columns
        - If no columns are specified, fills missing values across the full
        DataFrame
        - Counts missing values before and after filling
        - Records the operation in `cleaning_history`
        - Either updates `self.cleaned_data` or returns a preview copy
        - When `inplace=True`, the updated cleaned dataset may also be saved as a
        CSV file under `Cleaned_Dataset`

        History Details
        ---------------
        The recorded history entry includes:
        - `target_columns`
        - `fill_value`
        - `filled_cells`
        - `inplace`

        Side Effects
        ------------
        May update `self.cleaned_data`, append a history record, save the updated
        cleaned dataset to disk when `inplace=True`, and print preview or update
        messages.

        Notes
        -----
        This method is intended for fixed-value filling only, not statistic-based
        imputation such as mean, median, or mode.
        """
        if not self._validation():
            return None

        # ---------- Check missing columns ----------
        if target_columns is not None:
            missing_cols = [
                col for col in target_columns if col not in self.cleaned_data.columns
            ]
            if missing_cols:
                print(f"⚠️ Columns not found: {missing_cols} ‼️")
                return None

            # ---------- Fill values for selected columns ----------
            cleaning_data = self.cleaned_data.copy()
            before_missing = cleaning_data[target_columns].isna().sum().sum()
            cleaning_data[target_columns] = cleaning_data[target_columns].fillna( # Fill value to certain columns
                fill_value
            )
            after_missing = cleaning_data[target_columns].isna().sum().sum()

        else:
            # ---------- Filling values for all columns ----------
            cleaning_data = self.cleaned_data.fillna(fill_value).copy()
            before_missing = self.cleaned_data.isna().sum().sum()
            after_missing = cleaning_data.isna().sum().sum()

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,  # Record data after cleaning
            action="fill_values_in_data",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "target_columns": target_columns,
                "fill_value": fill_value,
                "filled_cells": int(before_missing - after_missing),
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data
        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data

    # -------------------- Strip whitespace in string values --------------------
    def strip_string_values(
        self,
        target_columns: list[str] = None,
        inplace: bool = False,
    ):
        """
        Strip surrounding whitespace from string-like values.

        This method trims leading and trailing whitespace from string entries in the
        working dataset. It can operate on specified columns or automatically on
        all object/string-like columns when `target_columns` is `None`.

        Parameters
        ----------
        target_columns : list[str], optional
            Column names to process. If `None`, all columns with dtype `object` or
            `string` are selected automatically.
        inplace : bool, default=False
            If `True`, update `self.cleaned_data` with the cleaned result.
            If `False`, return a cleaned preview without modifying the class state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame with stripped string values, or `None` if validation
            fails, no string-like columns are found, or requested columns are
            invalid.

        Behavior
        --------
        - Validates the working dataset
        - Automatically selects string-like columns if `target_columns` is `None`
        - Validates target column existence
        - Copies the working dataset
        - Applies `str.strip()` only to cell values that are actual strings
        - Counts how many cells changed after stripping
        - Records the action in `cleaning_history`
        - Either updates `self.cleaned_data` or returns a preview copy
        - When `inplace=True`, the updated cleaned dataset may also be saved as a
        CSV file under `Cleaned_Dataset`

        History Details
        ---------------
        The recorded history entry includes:
        - `target_columns`
        - `changed_cells`
        - `inplace`

        Side Effects
        ------------
        May update `self.cleaned_data`, append a history record, save the updated
        cleaned dataset to disk when `inplace=True`, and print preview or update
        messages.

        Notes
        -----
        This method is useful for standardizing textual values before performing
        replacement, grouping, merging, or categorical analysis.
        """
        if not self._validation():
            return None

        # ---------- Auto select string-like columns ----------
        if target_columns is None:
            target_columns = self.cleaned_data.select_dtypes(
                include=["object", "string"] # Filter "object-" and "string-" type column
            ).columns.tolist()

            # ---------- Check string-like columns in all data ----------
            if not target_columns:
                print("⚠️ No string-like columns available for stripping ‼️")
                return None

        # ---------- Check missing columns ----------
        missing_cols = [
            col for col in target_columns if col not in self.cleaned_data.columns
        ]
        if missing_cols:
            print(f"⚠️ Columns not found: {missing_cols} ‼️")
            return None

        cleaning_data = self.cleaned_data.copy()

        # ---------- Count changed cells before stripping ----------
        changed_cells = 0

        for col in target_columns:
            original_series = cleaning_data[col].copy()

            # Only strip non-null string values
            cleaning_data[col] = cleaning_data[col].apply(
                lambda x: x.strip() if isinstance(x, str) else x
            )

            changed_cells += int((original_series != cleaning_data[col]).sum())

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,  # Record data after cleaning
            action="strip_string_values",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "target_columns": target_columns,
                "changed_cells": changed_cells,
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data
        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data

    # -------------------- Replace values in data --------------------
    def replace_values_core(
        self,
        to_replace,
        value,
        target_columns: list[str] = None,
        inplace: bool = False,
    ):
        """
        Replace specified values in the working dataset.

        This method replaces occurrences of ``to_replace`` with ``value`` either
        across the entire DataFrame or within selected columns. It supports common
        data-cleaning tasks such as converting sentinel strings into missing values,
        standardizing categorical values, and collapsing multiple raw labels into a
        single normalized value.

        Parameters
        ----------
        to_replace : Any
            Value or collection of values to replace. Must not be ``None``.

            Supported forms typically include:

            - scalar values such as ``"N/A"`` or ``0``
            - iterable collections such as ``list``, ``tuple``, or ``set`` for
            many-to-one replacement
            - dictionary-style mappings supported by ``pandas.DataFrame.replace()``

        value : Any
            Replacement value assigned wherever ``to_replace`` is matched.

            In common one-to-one and many-to-one workflows, this is a single target
            value such as ``"missing"``, ``"unknown"``, or ``pd.NA``.
        target_columns : list[str], optional
            Column names to apply replacement to. If ``None``, replacement is
            applied across the full DataFrame.
        inplace : bool, default=False
            If ``True``, update ``self.cleaned_data`` with the cleaned result.
            If ``False``, return a cleaned preview without modifying the class
            state.

        Returns
        -------
        pandas.DataFrame or None
            Cleaned DataFrame with replaced values, or ``None`` if validation
            fails or parameters are invalid.

        Behavior
        --------
        - Validates the working dataset
        - Validates ``to_replace``
        - Optionally validates ``target_columns``
        - Copies the working dataset
        - Applies pandas ``replace()`` either globally or on selected columns
        - Estimates how many cells changed during replacement
        - Records the action in ``cleaning_history``
        - Either updates ``self.cleaned_data`` or returns a preview copy
        - When ``inplace=True``, the updated cleaned dataset may also be saved as a
        CSV file under ``Cleaned_Dataset``

        Changed-Cell Counting
        ---------------------
        The method uses slightly different counting strategies depending on the
        replacement pattern:

        - When replacing across the full DataFrame with non-dictionary
        ``to_replace``, the method estimates changed cells by comparing the number
        of matched target values before and after replacement.
        - When ``to_replace`` is dictionary-like, the method estimates changed cells
        by directly comparing the pre-replacement and post-replacement DataFrames.
        - When ``target_columns`` is specified, the method compares the selected
        subset before and after replacement to count changed cells.

        History Details
        ---------------
        The recorded history entry includes:
        - ``target_columns``
        - ``to_replace``
        - ``value``
        - ``changed_cells``
        - ``inplace``

        Side Effects
        ------------
        May update ``self.cleaned_data``, append a history record, save the updated
        cleaned dataset to disk when ``inplace=True``, and print preview or update
        messages.

        Notes
        -----
        This method is useful for:
        - replacing fake missing-value markers such as ``"unknown"``, ``"N/A"``, or
        ``"na"``
        - normalizing categorical values
        - converting placeholder codes into meaningful values
        - performing many-to-one replacement such as
        ``["N/A", "na", "unknown"] -> "missing"``

        Depending on ``to_replace``, pandas replacement behavior may vary for
        scalar, iterable, or dictionary-style replacement patterns.

        In the current terminal workflow, the menu layer may pass comma-separated
        user input through ``input_list()``, which typically arrives here as a
        ``list[str]`` for many-to-one replacement.
        """
        if not self._validation():
            return None

        if to_replace is None:
            print("⚠️ to_replace cannot be None ‼️")
            return None

        # ---------- Check missing columns ----------
        if target_columns is not None:
            missing_cols = [
                col for col in target_columns if col not in self.cleaned_data.columns
            ]
            if missing_cols:
                print(f"⚠️ Columns not found: {missing_cols} ‼️")
                return None

        cleaning_data = self.cleaned_data.copy()

        # ---------- Replace values ----------
        if target_columns is None:
            before_matches = (
                cleaning_data.isin(
                    [to_replace]
                    if not isinstance(to_replace, (list, tuple, set, dict))
                    else to_replace if not isinstance(to_replace, dict) else []
                )
                .sum()
                .sum()
                if not isinstance(to_replace, dict)
                else None
            )

            cleaning_data = cleaning_data.replace(to_replace=to_replace, value=value)

            if isinstance(to_replace, dict):
                changed_cells = int((self.cleaned_data != cleaning_data).sum().sum())
            else:
                after_matches = (
                    cleaning_data.isin(
                        [to_replace]
                        if not isinstance(to_replace, (list, tuple, set))
                        else to_replace
                    )
                    .sum()
                    .sum()
                )
                changed_cells = int(before_matches - after_matches)

        else:
            before_subset = cleaning_data[target_columns].copy()

            cleaning_data[target_columns] = cleaning_data[target_columns].replace(
                to_replace=to_replace,
                value=value,
            )

            changed_cells = int(
                (before_subset != cleaning_data[target_columns]).sum().sum()
            )

        # ---------- cleaning history ----------
        before_shape = self.cleaned_data.shape
        after_shape = cleaning_data.shape

        self._record_history(
            data_for_report=cleaning_data,  # Record data after cleaning
            action="replace_values",
            before_shape=before_shape,
            after_shape=after_shape,
            details={
                "target_columns": target_columns,
                "to_replace": to_replace,
                "value": value,
                "changed_cells": changed_cells,
                "inplace": inplace,
            },
        )

        # ---------- Update data ----------
        if inplace:
            self.cleaned_data = cleaning_data
            self._save_cleaned_dataset()
            print("🔥 Data updated")
            print(f"🔥 Previewing cleaned data\n{self.cleaned_data}")
            return self.cleaned_data
        else:
            print(f"🔎 Previewing cleaned data (no update)\n{cleaning_data}")
            return cleaning_data


# =================================================
