# -------------------- Import Modules --------------------
import os

import pandas as pd

from Cornus.Data_Hunter.HuntingDataCore import HuntingDataCore
from Cornus.MetaUnits.ClarityCore import ClarityCore

BASED_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CSV_DIR = os.path.join(BASED_PATH, "Transform_View")

os.makedirs(CSV_DIR, exist_ok=True)


# -------------------- TransViewCore --------------------
class TransViewCore:
    """
    Data transformation and reshaping core for tabular view-conversion workflows.

    `TransViewCore` is the dedicated transformation-view layer of the project. It
    receives the uploaded source data from `HuntingDataCore` and the cleaned working
    dataset from `ClarityCore`, then provides structure-changing operations such as
    stacking, unstacking, melting, pivoting, and pivot-table generation.

    Purpose
    -------
    The class centralizes common DataFrame reshaping operations used after data
    loading and optional cleaning. Unlike the cleaning layer, this class focuses on
    changing the structural presentation of the dataset rather than correcting,
    filtering, or replacing raw values.

    Design Principle
    ----------------
    This core is intended for independent view conversion rather than chained
    transformation pipelines. Each public transformation method starts from the
    baseline dataset stored in `self.cleaned_data` so that users can inspect the
    same dataset in different structural formats without automatically inheriting
    the previous transformation result.

    Data Flow
    ---------
    - `source_data` stores the original dataset loaded from `HuntingDataCore`
    - `cleaned_data` stores the cleaned baseline dataset obtained from `ClarityCore`
    - `transview_data` stores only the most recent transformation result when
    `inplace=True`
    - `trans_view_report` stores the latest transformation summary generated by
    `_record_transform_report()`

    Attributes
    ----------
    hunter_core : HuntingDataCore
        Data-loading core that provides the original target dataset and, when
        available, the current input file path used for naming exported results.
    clarity_core : ClarityCore
        Cleaning core that provides the cleaned baseline dataset used by
        transformation methods.
    source_data : pandas.DataFrame or None
        Original dataset loaded from `HuntingDataCore`.
    cleaned_data : pandas.DataFrame or None
        Baseline dataset used by transformation methods.
    transview_data : pandas.DataFrame or None
        Most recent transformation result stored only when `inplace=True`.
        It is not used as the default input source for later transformation
        methods.
    trans_view_report : dict or None
        Dictionary containing the latest transformation summary, including the
        action name, input/output shape, output path, and method-specific details.

    General Behavior
    ----------------
    Most public transformation methods:
    - validate the baseline dataset
    - optionally validate required columns
    - create a working DataFrame copy from `self.cleaned_data`
    - apply one reshaping operation
    - export the result to CSV through `_record_transform_report()`
    - update `self.trans_view_report` with the latest summary
    - optionally assign the result back to `self.transview_data` when
    `inplace=True`
    - return the transformed result as a pandas DataFrame

    Transformation Coverage
    -----------------------
    The class currently supports:
    - `stack_core()` for stacking columns into rows
    - `unstack_core()` for expanding index levels back into columns
    - `melt_core()` for long-format reshaping
    - `pivot_core()` for wide-format reshaping without aggregation
    - `pivot_table_core()` for wide-format reshaping with aggregation

    Notes
    -----
    This class is intended to keep transformation-view concerns separate from
    loading, inspection, and cleaning concerns. That separation helps keep the
    overall project easier to maintain, extend, test, and reuse.
    """

    # -------------------- Initialization --------------------
    def __init__(self, hunter_core: HuntingDataCore, clarity_core: ClarityCore):
        """
        Initialize the transformation-view core with original and cleaned data sources.

        Parameters
        ----------
        hunter_core : HuntingDataCore
            A `HuntingDataCore` instance that contains the originally loaded target
            dataset and may also provide the current input file path used for exported
            transformation result naming.
        clarity_core : ClarityCore
            A `ClarityCore` instance that contains the cleaned dataset used as the
            baseline transformation source.

        Attributes Initialized
        ----------------------
        hunter_core : HuntingDataCore
            Stored reference to the incoming loading core.
        clarity_core : ClarityCore
            Stored reference to the incoming cleaning core.
        source_data : pandas.DataFrame or None
            Raw loaded dataset from `hunter_core.target_data`.
        cleaned_data : pandas.DataFrame or None
            Cleaned baseline dataset from `clarity_core.cleaned_data`.
        transview_data : pandas.DataFrame or None
            Placeholder for the most recent transformation result. It is initialized as
            `None` and is updated only when a transformation method is executed with
            `inplace=True`.
        trans_view_report : dict or None
            Placeholder for the latest transformation report summary.

        Notes
        -----
        `source_data` is preserved as the original loaded snapshot. `cleaned_data`
        serves as the baseline input for all transformation methods. `transview_data`
        does not act as the default working source; it is used only to store the most
        recent transformation result when requested.
        """
        # ---------- Cores initialization / Data and records setup ----------
        self.hunter_core = hunter_core  # HuntingDataCore object
        self.clarity_core = clarity_core  # ClarityCore object

        self.source_data = hunter_core.target_data  # HuntingDataCore loaded target data

        self.cleaned_data = clarity_core.cleaned_data  # ClarityCore cleaned data
        self.transview_data = None
        self.trans_view_report: dict = None  # Record transformed view report

    # -------------------- Validation (helper) --------------------
    def _validation(self):
        """
        Validate whether the baseline transformation dataset is available and processable.

        This helper verifies that `self.cleaned_data` exists, is a pandas DataFrame,
        and is not empty before any transformation operation proceeds.

        Returns
        -------
        bool
            `True` if `self.cleaned_data` is available, is a DataFrame, and is not
            empty; otherwise `False`.

        Side Effects
        ------------
        Prints warning messages to the console when validation fails.

        Validation Rules
        ----------------
        The method checks whether:
        - `self.cleaned_data` is not `None`
        - `self.cleaned_data` is a pandas DataFrame
        - `self.cleaned_data` is not empty

        Notes
        -----
        This method is intended to be called at the beginning of public transformation
        methods because the class is designed to use `self.cleaned_data` as the default
        baseline input for reshaping operations.
        """
        if self.cleaned_data is None:
            print("⚠️ No Cleaned data available ‼️")
            return False

        if not isinstance(self.cleaned_data, pd.DataFrame):
            print("⚠️ Cleaned data must be a pandas DataFrame ‼️")
            return False

        if self.cleaned_data.empty:
            print("⚠️ Cleaned data is empty ‼️")
            return False

        return True

    # -------------------- Column validation (helper) --------------------
    def _validate_columns(self, columns: list[str]):
        """
        Validate whether the requested column list exists in the baseline transformation
        dataset.

        Parameters
        ----------
        columns : list[str]
            Column names that must exist in `self.cleaned_data.columns`.

        Returns
        -------
        bool
            `True` if `columns` is a non-empty list and every column exists in the
            baseline dataset; otherwise `False`.

        Side Effects
        ------------
        Prints warning messages to the console when validation fails.

        Validation Rules
        ----------------
        The method checks whether:
        - `columns` is not `None`
        - `columns` is a list
        - `columns` is not empty
        - all requested column names exist in `self.cleaned_data.columns`

        Notes
        -----
        This helper is intended for validating user-selected columns against the common
        baseline dataset used by transformation methods. When a method first modifies a
        local working copy, such as after `set_index()`, additional manual validation
        against the local transformed structure may still be needed.
        """
        if columns is None or not isinstance(columns, list) or len(columns) == 0:
            print("⚠️ Columns must be a non-empty list ‼️")
            return False

        missing_cols = [col for col in columns if col not in self.cleaned_data.columns]
        if missing_cols:
            print(f"⚠️ Columns not found: {missing_cols} ‼️")
            return False

        return True

    # -------------------- Transformation history (helper) --------------------
    def _record_transform_report(
        self,
        action: str,
        result_data: pd.DataFrame,
        details: dict = None,
        save_csv: bool = True,
    ):
        """
        Record one transformation result, update the latest transformation summary, and
        optionally export the transformed output to CSV.

        This helper centralizes two core responsibilities after a transformation
        operation has been completed:

        1. export the transformation result to a CSV file when requested
        2. update `self.trans_view_report` with a structured summary of the latest
        transformation

        Parameters
        ----------
        action : str
            Name of the transformation action being recorded, such as `"stack"`,
            `"unstack"`, `"melt"`, `"pivot"`, or `"pivot_table"`.
        result_data : pandas.DataFrame
            The transformed result DataFrame to summarize and optionally export.
        details : dict, optional
            Additional metadata describing the transformation. Typical examples include
            selected columns, index-setting columns, aggregation options, reset-index
            behavior, and `inplace` status. If `None`, an empty dictionary is used.
        save_csv : bool, default=True
            Whether to export `result_data` as a CSV file.

        Returns
        -------
        dict
            A transformation summary dictionary stored in `self.trans_view_report`.

        Recorded Fields
        ---------------
        The generated summary report contains:
        - `action`
        - `before_shape`
        - `after_shape`
        - `row_count`
        - `column_count`
        - `output_path`

        In addition, all key-value pairs from `details` are expanded directly into the
        same report dictionary.

        CSV Export Behavior
        -------------------
        When `save_csv=True`, the method exports the transformation result to a CSV file
        under `CSV_DIR`. If `hunter_core.current_file_path` is available, the output
        filename is constructed as:

        `{base_name}_{action}.csv`

        Otherwise, the fallback base name `"transformed_data"` is used.

        The file is saved with UTF-8 BOM encoding (`encoding="utf-8-sig"`), which is
        often convenient for spreadsheet tools.

        Shape Reporting Behavior
        ------------------------
        `before_shape` is derived from the baseline dataset currently stored in
        `self.cleaned_data`, while `after_shape` is derived from `result_data`.

        Because this class is designed to treat each transformation method as an
        independent view-conversion operation, `before_shape` represents the shape of
        the baseline input dataset rather than the shape of the most recent stored
        transformation result.

        Side Effects
        ------------
        - may export the transformation result to disk as a CSV file
        - updates `self.trans_view_report` with the latest transformation summary

        Notes
        -----
        This method is intended for internal use by public transformation methods and
        provides a single consistent mechanism for report generation and CSV export.
        """
        details = details or {}

        # ---------- Record shape before/after transforming ----------
        before_shape = (
            self.cleaned_data.shape
            if isinstance(self.cleaned_data, pd.DataFrame)
            else None
        )
        after_shape = (
            result_data.shape if isinstance(result_data, pd.DataFrame) else None
        )

        # ---------- Get data name as file's name and save as CSV ----------
        current_file_path = getattr(self.hunter_core, "current_file_path", None)
        if current_file_path:
            base_name = os.path.splitext(os.path.basename(current_file_path))[0]
        else:
            base_name = "transformed_data"

        save_path = None
        if save_csv:
            save_path = os.path.join(CSV_DIR, f"{base_name}_{action}.csv")
            result_data.to_csv(save_path, index=True, encoding="utf-8-sig")

        # ---------- Record transforming report ----------
        self.trans_view_report = {
            "action": action,
            "before_shape": before_shape,
            "after_shape": after_shape,
            "row_count": after_shape[0] if after_shape else None,
            "column_count": after_shape[1] if after_shape else None,
            "output_path": save_path,
            **details,
        }

        return self.trans_view_report

    # -------------------- Stack --------------------
    def stack_core(
        self,
        selected_columns: list[str] = None,
        set_index: list[str] = None,
        dropna: bool = True,
        reset_index: bool = False,
        inplace: bool = False,
    ):
        """
        Stack columns into rows for reshaping wide-form data into a long-form
        structure.

        This method transforms one or more columns of the working dataset into a
        stacked row-oriented representation. It may optionally set one or more columns
        as the index before stacking, optionally select a subset of columns to stack,
        optionally reset the resulting index, record a transformation report, export
        the result to CSV, and optionally update `self.transview_data`.

        Parameters
        ----------
        selected_columns : list[str], optional
            Column names to stack after any optional `set_index()` operation. If
            `None`, all remaining columns in the working dataset are stacked.
        set_index : list[str], optional
            Column names to move into the index before stacking. This is useful when
            identifier columns should remain as structural labels rather than being
            stacked as values.
        dropna : bool, default=True
            Whether missing values should be dropped during stacking.
        reset_index : bool, default=False
            If `True`, reset the resulting index after stacking so the output becomes a
            regular flat DataFrame.
        inplace : bool, default=False
            If `True`, update `self.transview_data` with the stacked result after the
            report has been recorded. If `False`, keep the current working dataset
            unchanged.

        Returns
        -------
        pandas.DataFrame or None
            Stacked result as a DataFrame, or `None` if validation fails.

        Behavior
        --------
        - validates the current working dataset
        - optionally validates columns used for `set_index`
        - optionally validates stack target columns after index-setting
        - stacks the selected or remaining columns using pandas `stack()`
        - converts the stacked result to a DataFrame named `"stack_value"`
        - optionally resets the index
        - records the transformation summary in `self.trans_view_report`
        - exports the result to CSV
        - optionally updates `self.transview_data`

        Report Details
        --------------
        The recorded transformation report includes:
        - `selected_columns`
        - `set_index`
        - `dropna`
        - `reset_index`
        - `inplace`

        Side Effects
        ------------
        - updates `self.trans_view_report`
        - may export the stacked result to a CSV file
        - may update `self.transview_data` when `inplace=True`
        - prints transformation report, result preview, and save status messages

        Notes
        -----
        This method is useful for converting wide-format datasets into stacked or
        longer structural views. When identifier columns exist, it is often preferable
        to provide `set_index` so those identifiers remain structural labels rather
        than being stacked as ordinary values.
        """
        if not self._validation():
            return None

        transformed_data = self.cleaned_data.copy()

        # ---------- Set index ----------
        if set_index is not None:
            if not self._validate_columns(set_index):
                return None
            transformed_data = transformed_data.set_index(set_index)

        # ---------- Select columns to stack ----------
        if selected_columns is not None:
            missing_cols = [
                col for col in selected_columns if col not in transformed_data.columns
            ]
            if missing_cols:
                print(f"⚠️ Columns not found after setting index: {missing_cols} ‼️")
                return None
            transformed_data = transformed_data[selected_columns]

        # ---------- Stack process ----------
        stacked_data = transformed_data.stack(dropna=dropna).to_frame(
            name="stack_value"
        )

        # ---------- Reset index if needed ----------
        if reset_index:
            stacked_data = stacked_data.reset_index()

        # ---------- Record report and save CSV ----------
        self._record_transform_report(
            action="stack",
            result_data=stacked_data,
            details={
                "selected_columns": selected_columns,
                "set_index": set_index,
                "dropna": dropna,
                "reset_index": reset_index,
                "inplace": inplace,
            },
        )

        # ---------- Update original data ----------
        if inplace:
            self.transview_data = stacked_data.copy()
            print(f"🕯️ Update original data")

        print(f"🔥 Transformed data report\n{self.trans_view_report}")
        print(f"🔎 Previewing stacked data\n{stacked_data}")
        print(f"📦 Stack result saved\n{'-'*100}")

        return stacked_data

    # -------------------- Unstack --------------------
    def unstack_core(
        self,
        set_index: list[str] = None,
        selected_columns: list[str] = None,
        level: int | str = -1,
        fill_value=None,
        reset_index: bool = False,
        inplace: bool = False,
    ):
        """
        Expand one index level of the working dataset back into columns.

        This method performs the inverse-style structural operation of `stack()` by
        moving one level of a MultiIndex row structure back into the column axis. It
        may optionally set one or more columns as the index before unstacking,
        optionally select a subset of columns before the operation, optionally reset
        the resulting index, record a transformation report, export the result to CSV,
        and optionally update `self.transview_data`.

        Parameters
        ----------
        set_index : list[str], optional
            Column names to move into the index before unstacking. This is commonly
            used to create the MultiIndex structure required by `unstack()`.
        selected_columns : list[str], optional
            Column names to retain before unstacking. If `None`, all available columns
            in the transformed working structure are used.
        level : int or str, default=-1
            Index level to unstack. By default, the innermost index level is expanded
            into columns.
        fill_value : Any, optional
            Value used to replace missing combinations generated during unstacking.
            This is useful when structural expansion introduces naturally absent
            combinations that would otherwise appear as missing values.
        reset_index : bool, default=False
            If `True`, reset the resulting index after unstacking so the output becomes
            a flatter DataFrame.
        inplace : bool, default=False
            If `True`, update `self.transview_data` with the unstacked result after the
            report has been recorded. If `False`, keep the current working dataset
            unchanged.

        Returns
        -------
        pandas.DataFrame or None
            Unstacked result as a DataFrame, or `None` if validation fails, the working
            index is not a MultiIndex, or the requested unstack level is invalid.

        Behavior
        --------
        - validates the current working dataset
        - optionally validates columns used for `set_index`
        - optionally validates retained columns after index-setting
        - checks whether the working index is a pandas MultiIndex
        - attempts to unstack the requested level using pandas `unstack()`
        - converts Series output to a DataFrame when necessary
        - optionally resets the index
        - records the transformation summary in `self.trans_view_report`
        - exports the result to CSV
        - optionally updates `self.transview_data`

        Report Details
        --------------
        The recorded transformation report includes:
        - `set_index`
        - `selected_columns`
        - `level`
        - `fill_value`
        - `reset_index`
        - `inplace`

        Side Effects
        ------------
        - updates `self.trans_view_report`
        - may export the unstacked result to a CSV file
        - may update `self.transview_data` when `inplace=True`
        - prints transformation report, result preview, and save status messages

        Notes
        -----
        `unstack()` requires a MultiIndex index structure. In practice, this often
        means `set_index` should contain at least two columns before unstacking.
        Even when the source data has already been cleaned, `fill_value` can still be
        useful because unstacking may introduce missing combinations as a result of the
        new structural layout rather than because of dirty input data.
        """
        if not self._validation():
            return None

        transformed_data = self.cleaned_data.copy()

        # ---------- Set index ----------
        if set_index is not None:
            if not self._validate_columns(set_index):
                return None
            transformed_data = transformed_data.set_index(set_index)

        # ---------- Select columns before unstack ----------
        if selected_columns is not None:
            missing_cols = [
                col for col in selected_columns if col not in transformed_data.columns
            ]
            if missing_cols:
                print(f"⚠️ Columns not found after setting index: {missing_cols} ‼️")
                return None
            transformed_data = transformed_data[selected_columns]

        # ---------- Check MultiIndex ----------
        if not isinstance(transformed_data.index, pd.MultiIndex):
            print(
                "⚠️ Unstack requires a MultiIndex index. Please provide set_index with at least two columns ‼️"
            )
            return None

        # ---------- Unstack process ----------
        try:
            unstacked_data = transformed_data.unstack(
                level=level, fill_value=fill_value
            )
        except (KeyError, IndexError, ValueError) as e:
            print(f"⚠️ Unstack failed: {e} ‼️")
            return None

        # ---------- Ensure DataFrame ----------
        if isinstance(unstacked_data, pd.Series):
            unstacked_data = unstacked_data.to_frame(name="unstack_value")

        # ---------- Reset index if needed ----------
        if reset_index:
            unstacked_data = unstacked_data.reset_index()

        # ---------- Record report and save CSV ----------
        self._record_transform_report(
            action="unstack",
            result_data=unstacked_data,
            details={
                "set_index": set_index,
                "selected_columns": selected_columns,
                "level": level,
                "fill_value": fill_value,
                "reset_index": reset_index,
                "inplace": inplace,
            },
        )

        # ---------- Update original data ----------
        if inplace:
            self.transview_data = unstacked_data.copy()
            print(f"🕯️ Update original data")

        print(f"🔥 Transformed data report\n{self.trans_view_report}")
        print(f"🔎 Previewing unstacked data\n{unstacked_data}")
        print(f"📦 Unstack result saved\n{'-'*100}")

        return unstacked_data

    # -------------------- Melt --------------------
    def melt_core(
        self,
        id_vars: list[str] = None,
        value_vars: list[str] = None,
        var_name: str = "variable",
        value_name: str = "value",
        ignore_index: bool = True,
        inplace: bool = False,
    ):
        """
        Reshape the working dataset from wide format to long format using pandas
        `melt()`.

        This method transforms one or more value columns into a two-column
        variable/value representation while preserving optional identifier columns. It
        records a transformation report, exports the result to CSV, and may optionally
        update `self.transview_data`.

        Parameters
        ----------
        id_vars : list[str], optional
            Column names to preserve as identifier variables. These columns remain in
            place while other columns are unpivoted into variable/value pairs.
        value_vars : list[str], optional
            Column names to unpivot into the long-format variable/value representation.
            If `None`, pandas will use all columns not listed in `id_vars`.
        var_name : str, default="variable"
            Name of the output column that stores former column labels.
        value_name : str, default="value"
            Name of the output column that stores the corresponding values.
        ignore_index : bool, default=True
            Whether to ignore the original row index in the melted result. If `True`,
            the output receives a new default integer index. If `False`, original index
            values are preserved and may repeat after expansion.
        inplace : bool, default=False
            If `True`, update `self.transview_data` with the melted result after the
            report has been recorded. If `False`, keep the current working dataset
            unchanged.

        Returns
        -------
        pandas.DataFrame or None
            Melted result as a DataFrame, or `None` if validation fails.

        Behavior
        --------
        - validates the current working dataset
        - optionally validates `id_vars`
        - optionally validates `value_vars`
        - reshapes the dataset using pandas `melt()`
        - records the transformation summary in `self.trans_view_report`
        - exports the result to CSV
        - optionally updates `self.transview_data`

        Report Details
        --------------
        The recorded transformation report includes:
        - `id_vars`
        - `value_vars`
        - `var_name`
        - `value_name`
        - `ignore_index`
        - `inplace`

        Side Effects
        ------------
        - updates `self.trans_view_report`
        - may export the melted result to a CSV file
        - may update `self.transview_data` when `inplace=True`
        - prints transformation report, result preview, and save status messages

        Notes
        -----
        This method is often more intuitive than `stack()` for standard wide-to-long
        reshaping because it operates directly on named columns rather than index
        levels. It is especially useful when a dataset contains identifier columns and
        several measurement columns that should be gathered into a tidy long format.
        """
        if not self._validation():
            return None

        transformed_data = self.cleaned_data.copy()

        # ---------- Validate id_vars ----------
        if id_vars is not None:
            if not self._validate_columns(id_vars):
                return None

        # ---------- Validate value_vars ----------
        if value_vars is not None:
            if not self._validate_columns(value_vars):
                return None

        # ---------- Melt process ----------
        melted_data = pd.melt(
            transformed_data,
            id_vars=id_vars,
            value_vars=value_vars,
            var_name=var_name,
            value_name=value_name,
            ignore_index=ignore_index,
        )

        # ---------- Record report and save CSV ----------
        self._record_transform_report(
            action="melt",
            result_data=melted_data,
            details={
                "id_vars": id_vars,
                "value_vars": value_vars,
                "var_name": var_name,
                "value_name": value_name,
                "ignore_index": ignore_index,
                "inplace": inplace,
            },
        )

        # ---------- Update original data ----------
        if inplace:
            self.transview_data = melted_data.copy()
            print(f"🕯️ Update original data")

        print(f"🔥 Transformed data report\n{self.trans_view_report}")
        print(f"🔎 Previewing melted data\n{melted_data}")
        print(f"📦 Melt result saved\n{'-'*100}")

        return melted_data

    # -------------------- Pivot table --------------------
    def pivot_table_core(
        self,
        index: list[str] = None,
        columns: list[str] = None,
        values: list[str] = None,
        aggfunc: str | list | dict = "mean",
        fill_value=None,
        margins: bool = False,
        dropna: bool = True,
        reset_index: bool = False,
        inplace: bool = False,
    ):
        """
        Create a pivot table from the working dataset using aggregation.

        This method reshapes the working dataset into a summarized wide-format table by
        grouping over one or more index columns and column-group columns, then applying
        an aggregation function to the selected value columns. It records a
        transformation report, exports the result to CSV, and may optionally update
        `self.transview_data`.

        Parameters
        ----------
        index : list[str], optional
            Column names to use as the row index of the pivot table.
        columns : list[str], optional
            Column names to use as the column grouping axis of the pivot table.
        values : list[str], optional
            Column names containing values to aggregate.
        aggfunc : str or list or dict, default="mean"
            Aggregation function specification passed to pandas `pivot_table()`. Common
            examples include `"mean"`, `"sum"`, `"count"`, or multiple functions.
        fill_value : Any, optional
            Value used to replace missing results in the pivot table.
        margins : bool, default=False
            Whether to add row and column subtotal / grand total margins.
        dropna : bool, default=True
            Whether columns whose entries are all missing should be excluded in the
            resulting pivot table according to pandas behavior.
        reset_index : bool, default=False
            If `True`, reset the resulting index after building the pivot table so the
            output becomes flatter and easier to view or export.
        inplace : bool, default=False
            If `True`, update `self.transview_data` with the pivot-table result after
            the report has been recorded. If `False`, keep the current working dataset
            unchanged.

        Returns
        -------
        pandas.DataFrame or None
            Pivot-table result as a DataFrame, or `None` if validation fails.

        Behavior
        --------
        - validates the current working dataset
        - optionally validates `index`
        - optionally validates `columns`
        - optionally validates `values`
        - builds a pivot table using pandas `pivot_table()`
        - converts Series output to a DataFrame when necessary
        - optionally resets the index
        - records the transformation summary in `self.trans_view_report`
        - exports the result to CSV
        - optionally updates `self.transview_data`

        Report Details
        --------------
        The recorded transformation report includes:
        - `index`
        - `columns`
        - `values`
        - `aggfunc`
        - `fill_value`
        - `margins`
        - `dropna`
        - `reset_index`
        - `inplace`

        Side Effects
        ------------
        - updates `self.trans_view_report`
        - may export the pivot-table result to a CSV file
        - may update `self.transview_data` when `inplace=True`
        - prints transformation report, result preview, and save status messages

        Notes
        -----
        Unlike `pivot_core()`, this method supports aggregation and is therefore the
        preferred choice when the combination of `index` and `columns` is not unique in
        the source data. It is useful for summary reporting, cross-tab style views, and
        aggregated analytical reshaping.
        """
        if not self._validation():
            return None

        transformed_data = self.cleaned_data.copy()

        # ---------- Validate index ----------
        if index is not None:
            if not self._validate_columns(index):
                return None

        # ---------- Validate columns ----------
        if columns is not None:
            if not self._validate_columns(columns):
                return None

        # ---------- Validate values ----------
        if values is not None:
            if not self._validate_columns(values):
                return None

        # ---------- Pivot table process ----------
        pivot_table_data = pd.pivot_table(
            transformed_data,
            index=index,
            columns=columns,
            values=values,
            aggfunc=aggfunc,
            fill_value=fill_value,
            margins=margins,
            dropna=dropna,
        )

        # ---------- Ensure DataFrame ----------
        if isinstance(pivot_table_data, pd.Series):
            pivot_table_data = pivot_table_data.to_frame(name="pivot_table_value")

        # ---------- Reset index if needed ----------
        if reset_index:
            pivot_table_data = pivot_table_data.reset_index()

        # ---------- Record report and save CSV ----------
        self._record_transform_report(
            action="pivot_table",
            result_data=pivot_table_data,
            details={
                "index": index,
                "columns": columns,
                "values": values,
                "aggfunc": aggfunc,
                "fill_value": fill_value,
                "margins": margins,
                "dropna": dropna,
                "reset_index": reset_index,
                "inplace": inplace,
            },
        )

        # ---------- Update original data ----------
        if inplace:
            self.transview_data = pivot_table_data.copy()
            print(f"🕯️ Update original data")

        print(f"🔥 Transformed data report\n{self.trans_view_report}")
        print(f"🔎 Previewing pivot table data\n{pivot_table_data}")
        print(f"📦 Pivot table result saved\n{'-'*100}")

        return pivot_table_data

    # -------------------- Pivot --------------------
    def pivot_core(
        self,
        index: list[str] = None,
        columns: list[str] = None,
        values: list[str] = None,
        reset_index: bool = False,
        inplace: bool = False,
    ):
        """
        Reshape the working dataset into wide format without aggregation.

        This method converts long-format data into a wide-format table by assigning one
        or more columns to the row index, one or more columns to the new column axis,
        and one or more value columns to the cell contents. It records a transformation
        report, exports the result to CSV, and may optionally update
        `self.transview_data`.

        Parameters
        ----------
        index : list[str], optional
            Column names to use as the row index of the pivoted result.
        columns : list[str], optional
            Column names whose unique values will become the new columns of the pivoted
            result.
        values : list[str], optional
            Column names containing the values to place into the pivoted cells.
        reset_index : bool, default=False
            If `True`, reset the resulting index after pivoting so the output becomes a
            flatter DataFrame.
        inplace : bool, default=False
            If `True`, update `self.transview_data` with the pivoted result after the
            report has been recorded. If `False`, keep the current working dataset
            unchanged.

        Returns
        -------
        pandas.DataFrame or None
            Pivoted result as a DataFrame, or `None` if validation fails or if pivoting
            fails because the requested index/column combinations are not unique.

        Behavior
        --------
        - validates the current working dataset
        - optionally validates `index`
        - optionally validates `columns`
        - optionally validates `values`
        - attempts to pivot the dataset using pandas `pivot()`
        - catches non-unique key-combination errors and instructs the user to use
        `pivot_table_core()` when aggregation is required
        - converts Series output to a DataFrame when necessary
        - optionally resets the index
        - records the transformation summary in `self.trans_view_report`
        - exports the result to CSV
        - optionally updates `self.transview_data`

        Report Details
        --------------
        The recorded transformation report includes:
        - `index`
        - `columns`
        - `values`
        - `reset_index`
        - `inplace`

        Side Effects
        ------------
        - updates `self.trans_view_report`
        - may export the pivoted result to a CSV file
        - may update `self.transview_data` when `inplace=True`
        - prints transformation report, result preview, and save status messages

        Notes
        -----
        This method does not perform aggregation. Therefore, it requires that each
        combination of `index` and `columns` correspond to at most one value record.
        If duplicate combinations exist, pandas raises an error and
        `pivot_table_core()` should be used instead.
        """
        if not self._validation():
            return None

        transformed_data = self.cleaned_data.copy()

        # ---------- Validate index ----------
        if index is not None:
            if not self._validate_columns(index):
                return None

        # ---------- Validate columns ----------
        if columns is not None:
            if not self._validate_columns(columns):
                return None

        # ---------- Validate values ----------
        if values is not None:
            if not self._validate_columns(values):
                return None

        try:
            # ---------- Pivot process ----------
            pivoted_data = transformed_data.pivot(
                index=index,
                columns=columns,
                values=values,
            )
        except ValueError as e:
            print(f"⚠️ Pivot failed: {e} ‼️")
            print(
                "⚠️ Pivot requires unique index/column combinations. Use pivot_table_core() if aggregation is needed ‼️"
            )
            return None

        # ---------- Ensure DataFrame ----------
        if isinstance(pivoted_data, pd.Series):
            pivoted_data = pivoted_data.to_frame(name="pivot_value")

        # ---------- Reset index if needed ----------
        if reset_index:
            pivoted_data = pivoted_data.reset_index()

        # ---------- Record report and save CSV ----------
        self._record_transform_report(
            action="pivot",
            result_data=pivoted_data,
            details={
                "index": index,
                "columns": columns,
                "values": values,
                "reset_index": reset_index,
                "inplace": inplace,
            },
        )

        # ---------- Update original data ----------
        if inplace:
            self.transview_data = pivoted_data.copy()
            print(f"🕯️ Update original data")

        print(f"🔥 Transformed data report\n{self.trans_view_report}")
        print(f"🔎 Previewing pivoted data\n{pivoted_data}")
        print(f"📦 Pivot result saved\n{'-'*100}")

        return pivoted_data


# =================================================
